import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import { Providers } from '@/components/Providers';

const roboto = Roboto({
	subsets: ['cyrillic', 'latin'],
});

export const metadata: Metadata = {
	title: 'Realtime Chat',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ru">
			<body className={roboto.className}>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
